auto: true
server: true
pygments: true
permalink: none
root_dir: ""
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
exclude:
- .gitignore
- README.md

# prose.io settings
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: 'source/_posts'
  siteurl: 'http://techblog.trunkclub.com'
  media: 'assets'
  metadata:
    source/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
          placeholder: "Trunk Botterson"
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "comments"
        field:
          element: checkbox
          label: "Comments"
          value: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
